<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CinemaManager.Wpf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CinemaManager.Application\CinemaManager.Application.csproj" />
    <ProjectReference Include="..\CinemaManager.Services\CinemaManager.Services.csproj" />
    <ProjectReference Include="..\CinemaManager.ViewModels\CinemaManager.ViewModels.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Posters\**\*" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Assets\Posters\" />
  </ItemGroup>
</Project>
